package org.demo.bpm;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(ce8338f297f4817e1d3e4aa92a72a763)
 */
@org.kie.api.definition.type.Label(value = "Approval Requirement")
public class Approval  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Boolean requireApproval;

    public Approval() {
    }

    public Approval(java.lang.Boolean requireApproval) {
        this.requireApproval = requireApproval;
    }


    
    public java.lang.Boolean getRequireApproval() {
        return this.requireApproval;
    }

    public void setRequireApproval(java.lang.Boolean requireApproval) {
        this.requireApproval = requireApproval;
    }
}