package org.demo.bpm;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(8c0c0ebb77cb9b8d0fb6d30ef7eed4fb)
 */
@org.kie.api.definition.type.Label(value = "Decision")
public class Decision  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean requireApproval;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.Date started;

    public Decision() {
    }

    public Decision(java.util.Date started, java.lang.Boolean requireApproval) {
        this.started = started;
        this.requireApproval = requireApproval;
    }


    
    public java.lang.Boolean getRequireApproval() {
        return this.requireApproval;
    }

    public void setRequireApproval(java.lang.Boolean requireApproval) {
        this.requireApproval = requireApproval;
    }
    
    public java.util.Date getStarted() {
        return this.started;
    }

    public void setStarted(java.util.Date started) {
        this.started = started;
    }
}