package org.demo.bpm;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(15593b152e5227350470c29d04a580d6)
 */
@org.kie.api.definition.type.ClassReactive
@org.kie.api.definition.type.Label(value = "Note")
public class noteData  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Budget Amount")
    @org.kie.api.definition.type.Position(value = 3)
    private java.math.BigDecimal budgetAmount;
    
    @org.kie.api.definition.type.Label(value = "Created Date")
    @org.kie.api.definition.type.Position(value = 8)
    private java.util.Date createdDate;
    
    @org.kie.api.definition.type.Label(value = "Is Approved")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Boolean isApproved;
    
    @org.kie.api.definition.type.Label(value = "Man Hours")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Long manHours;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Project")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String project;
    
    @org.kie.api.definition.type.Label(value = "Reason")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String rejectionReason;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Boolean requiresApproval;
    
    @org.kie.api.definition.type.Label(value = "Text")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String text;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Title")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String title;

    public noteData() {
    }

    public noteData(java.lang.String title, java.lang.String text, java.lang.String project, java.math.BigDecimal budgetAmount, java.lang.Long manHours, java.lang.Boolean isApproved, java.lang.Boolean requiresApproval, java.lang.String rejectionReason, java.util.Date createdDate) {
        this.title = title;
        this.text = text;
        this.project = project;
        this.budgetAmount = budgetAmount;
        this.manHours = manHours;
        this.isApproved = isApproved;
        this.requiresApproval = requiresApproval;
        this.rejectionReason = rejectionReason;
        this.createdDate = createdDate;
    }

    public noteData(java.lang.String title, java.lang.String project) {
        this.title = title;
        this.project = project;
    }
    
    public java.math.BigDecimal getBudgetAmount() {
        return this.budgetAmount;
    }

    public void setBudgetAmount(java.math.BigDecimal budgetAmount) {
        this.budgetAmount = budgetAmount;
    }
    
    public java.util.Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(java.util.Date createdDate) {
        this.createdDate = createdDate;
    }
    
    public java.lang.Boolean getIsApproved() {
        return this.isApproved;
    }

    public void setIsApproved(java.lang.Boolean isApproved) {
        this.isApproved = isApproved;
    }
    
    public java.lang.Long getManHours() {
        return this.manHours;
    }

    public void setManHours(java.lang.Long manHours) {
        this.manHours = manHours;
    }
    
    public java.lang.String getProject() {
        return this.project;
    }

    public void setProject(java.lang.String project) {
        this.project = project;
    }
    
    public java.lang.String getRejectionReason() {
        return this.rejectionReason;
    }

    public void setRejectionReason(java.lang.String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }
    
    public java.lang.Boolean getRequiresApproval() {
        return this.requiresApproval;
    }

    public void setRequiresApproval(java.lang.Boolean requiresApproval) {
        this.requiresApproval = requiresApproval;
    }
    
    public java.lang.String getText() {
        return this.text;
    }

    public void setText(java.lang.String text) {
        this.text = text;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        org.demo.bpm.noteData that = (org.demo.bpm.noteData)o;
        if (project != null ? !project.equals(that.project) : that.project != null) return false;
        if (title != null ? !title.equals(that.title) : that.title != null) return false;
        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (project != null ? project.hashCode() : 0);
        result = 31 * result + (title != null ? title.hashCode() : 0);
        return result;
    }
}